### ISSUE TITLE
Image Input Data

### ISSUE THREAD

**Issue by tirthadagr8** [DSCKGEC/OCR-TextRecognition#4]
https://github.com/DSCKGEC/OCR-TextRecognition/blob/4cc8f97aaf1e4a67b88e46d20a5f9821101fa678/OCR/OCRTextRecg.py#L49
Input the image name from which text is to be read.

**Comment by Abhilash1781** [comment]
this issue and that nontype object has no error both are similar bug ,so please assign this to me
