### ISSUE TITLE
East Text Detector Not Mentioned

### ISSUE THREAD

**Issue by tirthadagr8** [DSCKGEC/OCR-TextRecognition#6]
https://github.com/DSCKGEC/OCR-TextRecognition/blob/4cc8f97aaf1e4a67b88e46d20a5f9821101fa678/OCR/OCRTextRecg.py#L62
You have to input the east text detector file for proper detection of text.

**Comment by Abhilash1781** [comment]
hello sir , please assign this to me

**Comment by Abhilash1781** [comment]
https://www.dropbox.com/s/r2ingd0l3zt8hxs/frozen_east_text_detection.tar.gz?dl=1
Download the model using the above link , extract it . You will receive a .pb file . 
Copy and paste it to the working directory of the script 
Open working directory in command prompt  ,
Type  python OCRTextRecg.py -i=complete file path of the image -east=complete file path of East text detector
