### ISSUE TITLE
Set up a flask web server

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/OCR-TextRecognition#7]
**Describe the solution you'd like**
Set up a basic flask app with a single route.

**Additional context**
No need to set up any HTML, CSS for this. Only Making the routes will do

**Comment by SankalpM-29** [comment]
Hey @Codehackerone, you have some arguments to pass so that would take more time to write a flask app. Will you be okay if I create a [Gradio](https://gradio.app/) app which will also provide you with a GUI(HTML, CSS) on the frontend with minimal effort?

**Comment by Codehackerone** [comment]
Well, very interesting proposal. Can you please provide a quick walkthrough of how you are gonna do it?

**Comment by SankalpM-29** [comment]
![image](https://user-images.githubusercontent.com/87968608/180833318-a6647848-9835-4e78-8b21-52bae92ed1cf.png)

Here we are taking just one field as input but for your arguments we can add multiple fields and then pass on those values to your backend code which will then run rest of the code involving ocr.

**Comment by Codehackerone** [comment]
Okay, makes sense. What about deployment? How easy is that?

**Comment by SankalpM-29** [comment]
Ok, I tried to create the gradio app but was not able to pass the arguments to the function containing the OCR code.

![image](https://user-images.githubusercontent.com/87968608/181248653-fcdd13f3-e591-4975-b68b-02502f7b4073.png)

<br>

Here's the code if you want to [check it out.](https://github.com/SankalpM-29/OCR-TextRecognition/blob/a6d0c02f4aabe4368e5e9dc4049b3c3ed213dab6/OCR/demo.py)

Now if you want a flask app then you need to decide what things you are sending on the backend(and how) to create routes.

- what things -> arguments, image
- how(format) -> json, form-data

**Comment by Codehackerone** [comment]
Okay! I'll have a look

**Comment by Codehackerone** [comment]
Lets leave this for now. Create a Flask server, with 2 routes. 

Dont have to do anything else.

**Comment by SankalpM-29** [comment]
I have created a fastapi app as it's much simpler and better for deployment. 

[code for the app](https://github.com/SankalpM-29/OCR-TextRecognition/blob/53e69f35850ea891f7c668788426d86f536a52c5/OCR/app.py)

[Here's](https://fastapi.tiangolo.com/) the documentation for Fastapi. The main reason to use this is that you can directly check the routes that you have created without the need to download software like Postman or creating (HTML,CSS).

To check the created routes, start the server and go to **localhost/docs**

Now in our case if we go to this above mentioned route we will get the swagger interface like 

![image](https://user-images.githubusercontent.com/87968608/181617459-a99ee637-6fea-4c87-8a1f-76a3a82b9e52.png)

We just need to add
- image full path
- east file full path 

Then the rest of the code will be executed as before. This code will save the text detected image in the same folder where the app file is running.

**Comment by Codehackerone** [comment]
Great work. I'll have a thorough look and merge your pr.

**Comment by SankalpM-29** [comment]
After you're done just let me know; I'll open a pr to merge the 2 new files:
- app.py
- requirements.txt
