### ISSUE TITLE
Add a dashboard html page

### ISSUE THREAD

**Issue by Codehackerone** [DSCKGEC/OCR-TextRecognition#8]
**Describe the solution you'd like**
Add an HTML page for the dashboard, which will contain two containers side by side. Users will be able to upload an image to the left container and there should be a button to read the text and generate the text on the next container.

**Comment by A1zenSousuke** [comment]
@Codehackerone can I try this issue?

**Comment by Codehackerone** [comment]
Sure.

**Comment by A1zenSousuke** [comment]
@Codehackerone i have created the dashboard can you check it?
